server:
  port: 8080

spring:
  datasource:
    username: root
    password: test1234
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&userSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB

#showSql
logging:
  level:
    com:
      example:
        mapper : debug