server:
  port: 8080

spring:
  datasource:
    username: root
    password: test1234
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&userSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#showSql
logging:
  level:
    com:
      example:
        mapper : debug