server:
  port: 8080

spring:
  datasource:
    username: root
    password: fuimazv8p
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&userSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver


#jdbc:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#  username: root
#  password: fuimazv8p

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.hk.culture.mini.program.entity

#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**Mapper.xml
#  typeAliasesPackage: com.hk.culture.mini.program.entity
#  defaultStatementTimeout: 120
#  config-locations: classpath:config/mybatis-config.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug